/**
 * The icon set, held together.
 *
 * Every file here is referenced from somewhere that fails silently. A manifest
 * naming an icon that is not in public/ installs the app with a blank tile; a
 * <link> pointing at a missing path gets the browser's default page glyph; a
 * maskable icon with too little margin loses its top bar to Android's circle
 * crop and nobody sees it until the app is on a phone.
 *
 * All of it is generated by tools/brand/, so a failure here means the package
 * and the shell drifted apart — regenerate rather than patch a file by hand.
 */

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

const pub = (name: string) => new URL(`../public/${name}`, import.meta.url);
const read = (name: string) => readFileSync(pub(name), 'utf8');
const exists = (name: string) => {
  try {
    readFileSync(pub(name));
    return true;
  } catch {
    return false;
  }
};

const html = read('../index.html');
const manifest = JSON.parse(read('manifest.webmanifest')) as {
  icons: { src: string; sizes: string; purpose: string }[];
  theme_color: string;
  background_color: string;
};

test('every icon the manifest names is in public/', () => {
  for (const icon of manifest.icons) {
    assert.ok(icon.src.startsWith('/'), `${icon.src} is an absolute path`);
    assert.ok(exists(icon.src.slice(1)), `${icon.src} exists`);
  }
});

test('the manifest offers a maskable icon at both sizes', () => {
  // Without one, Android crops the `any` icon itself — and its circle cuts the
  // topmost bar, which is the widest one and the reason the mark reads as a
  // tree. The maskable build carries 26% margin for exactly that crop.
  for (const size of ['192x192', '512x512']) {
    assert.ok(
      manifest.icons.some((i) => i.purpose === 'maskable' && i.sizes === size),
      `a maskable icon at ${size}`,
    );
  }
});

test('every icon the shell links to is in public/', () => {
  const hrefs = [...html.matchAll(/<link[^>]+rel="(?:icon|apple-touch-icon|manifest)"[^>]*>/g)]
    .map((m) => /href="\/([^"]+)"/.exec(m[0] as string)?.[1])
    .filter((h): h is string => Boolean(h));
  assert.ok(hrefs.length >= 4, 'the shell links svg, ico, apple-touch and manifest');
  for (const href of hrefs) assert.ok(exists(href), `/${href} exists`);
});

test('/favicon.ico is present whether or not it is declared', () => {
  // Bookmark bars, Windows shortcuts and old feed readers request the path
  // directly. A 404 there is a blank icon, and no <link> prevents it.
  assert.ok(exists('favicon.ico'));
});

test('the favicon is the mark itself: four bars on the light tile', () => {
  /*
   * Both halves of this were wrong until ADR-0201, and both were visible only
   * where nothing else is: an installed application shows the small picture and
   * nothing around it. The tile was the ink one, so SONE sat black beside
   * SOTE's paper white; and the bars were the three-bar emergency build, so the
   * picture was not the logo the interface draws all day.
   */
  const svg = read('favicon.svg');
  assert.equal((svg.match(/<rect/g) ?? []).length, 5, 'a tile plus four bars');
  assert.match(svg, /<rect width="100" height="100" fill="#faf8f4"\/>/, 'on the paper tile');
  assert.match(svg, /fill="#2f7d6f"/, 'the third bar carries the light-ground accent');
  assert.doesNotMatch(svg, /fill="#6fc0b0"/, 'and not the dark-ground one');
});

test('the social card is served and described', () => {
  // A card whose image 404s renders as a bare text link, which is the same
  // outcome as having no tags at all.
  assert.ok(exists('og-image.png'));
  assert.match(html, /<meta property="og:image" content="\/og-image\.png" \/>/);
  assert.match(html, /<meta property="og:image:alt"/);
  assert.match(html, /<meta name="twitter:card" content="summary_large_image" \/>/);
});

test('the card describes the software and not the page', () => {
  // Everything in a SONE instance is behind a login, so a crawler only ever
  // sees this shell. og:title must stay the product name: a card that took its
  // title from the document would leak somebody's page title into a chat
  // preview the moment the shell learned to render one.
  assert.match(html, /<meta property="og:title" content="SONE" \/>/);
  assert.doesNotMatch(html, /<meta property="og:url"/);
});

test('the theme colours are the tokens and not near-misses', () => {
  assert.equal(manifest.background_color, '#faf8f4');
  assert.equal(manifest.theme_color, '#faf8f4');
  assert.match(html, /content="#faf8f4" media="\(prefers-color-scheme: light\)"/);
  assert.match(html, /content="#161615" media="\(prefers-color-scheme: dark\)"/);
});
